;              
CREATE USER IF NOT EXISTS SA SALT '7f99275425236b56' HASH '38dde53809333914c73bd5f639b79060998807c7519fe92a116dc4d161f202e1' ADMIN;            
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;        
CREATE CACHED TABLE PUBLIC.T_ADDRESS(
    PHONE VARCHAR(255),
    PHONE_TYPE VARCHAR(255),
    STREET VARCHAR(255),
    CITY_ID BIGINT,
    PERSON_ID BIGINT NOT NULL
);       
ALTER TABLE PUBLIC.T_ADDRESS ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(PERSON_ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_ADDRESS;
CREATE CACHED TABLE PUBLIC.T_AUDIT_LOG(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    AUDIT_DATE TIMESTAMP,
    ENTITY_CLASS VARCHAR(255),
    ENTITY_ID BIGINT,
    MESSAGE VARCHAR(255),
    USERNAME VARCHAR(255)
);            
ALTER TABLE PUBLIC.T_AUDIT_LOG ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_AUDIT_LOG;              
CREATE CACHED TABLE PUBLIC.T_CITY(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    NAME VARCHAR(255)
);              
ALTER TABLE PUBLIC.T_CITY ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_CITY;   
CREATE CACHED TABLE PUBLIC.T_CLINIC(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    NAME VARCHAR(255)
);            
ALTER TABLE PUBLIC.T_CLINIC ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_CLINIC; 
CREATE CACHED TABLE PUBLIC.T_CLINIC_PERSON(
    CLINIC_ID BIGINT NOT NULL,
    PERSON_ID BIGINT NOT NULL
);    
ALTER TABLE PUBLIC.T_CLINIC_PERSON ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(CLINIC_ID, PERSON_ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_CLINIC_PERSON;
CREATE CACHED TABLE PUBLIC.T_IMAGE_CONTENT(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    CONTENT BLOB
);     
ALTER TABLE PUBLIC.T_IMAGE_CONTENT ADD CONSTRAINT PUBLIC.CONSTRAINT_16 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_IMAGE_CONTENT;           
CREATE CACHED TABLE PUBLIC.T_IMAGE(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    FILE_PATH VARCHAR(255),
    HEIGHT INTEGER NOT NULL,
    NAME VARCHAR(255),
    WIDTH INTEGER NOT NULL,
    CONTENT_ID BIGINT,
    PET_ID BIGINT
);     
ALTER TABLE PUBLIC.T_IMAGE ADD CONSTRAINT PUBLIC.CONSTRAINT_1D PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_IMAGE;           
CREATE CACHED TABLE PUBLIC.T_OWNER(
    RATING INTEGER,
    ID BIGINT NOT NULL
);              
ALTER TABLE PUBLIC.T_OWNER ADD CONSTRAINT PUBLIC.CONSTRAINT_22 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_OWNER;  
CREATE CACHED TABLE PUBLIC.T_PERSON(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);  
ALTER TABLE PUBLIC.T_PERSON ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_PERSON; 
CREATE CACHED TABLE PUBLIC.T_PET(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    BIRTH_DATE DATE,
    NAME VARCHAR(255),
    OWNER_ID BIGINT,
    TYPE_ID BIGINT
); 
ALTER TABLE PUBLIC.T_PET ADD CONSTRAINT PUBLIC.CONSTRAINT_4C PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_PET;    
CREATE CACHED TABLE PUBLIC.T_PET_TYPE(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    NAME VARCHAR(255)
);          
ALTER TABLE PUBLIC.T_PET_TYPE ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_PET_TYPE;               
CREATE CACHED TABLE PUBLIC.T_SPECIALTY(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    NAME VARCHAR(255)
);         
ALTER TABLE PUBLIC.T_SPECIALTY ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_SPECIALTY;              
CREATE CACHED TABLE PUBLIC.T_VET(
    WORKS_FULL_TIME BOOLEAN,
    ID BIGINT NOT NULL
);       
ALTER TABLE PUBLIC.T_VET ADD CONSTRAINT PUBLIC.CONSTRAINT_4CC PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_VET;    
CREATE CACHED TABLE PUBLIC.T_VET_SPECIALTY(
    VET_ID BIGINT NOT NULL,
    SPECIALTY_ID BIGINT NOT NULL
);    
ALTER TABLE PUBLIC.T_VET_SPECIALTY ADD CONSTRAINT PUBLIC.CONSTRAINT_43 PRIMARY KEY(VET_ID, SPECIALTY_ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_VET_SPECIALTY;          
CREATE CACHED TABLE PUBLIC.T_VISIT(
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    DESCRIPTION CLOB,
    VISIT_DATE TIMESTAMP,
    PET_ID BIGINT,
    VISITS_ORDER INTEGER
);       
ALTER TABLE PUBLIC.T_VISIT ADD CONSTRAINT PUBLIC.CONSTRAINT_28 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.T_VISIT;  
ALTER TABLE PUBLIC.T_PERSON ADD CONSTRAINT PUBLIC.UK_RY4DT44G5WUF28YRWCS04JL6U UNIQUE(EMAIL);  
ALTER TABLE PUBLIC.T_CLINIC_PERSON ADD CONSTRAINT PUBLIC.UK_MRLKL7AIVBUN8SBXHS6HW2GYT UNIQUE(PERSON_ID);       
ALTER TABLE PUBLIC.T_VET ADD CONSTRAINT PUBLIC.FK33TBA4Y9Q47XK2KNV12CXT2WM FOREIGN KEY(ID) REFERENCES PUBLIC.T_PERSON(ID) NOCHECK;             
ALTER TABLE PUBLIC.T_CLINIC_PERSON ADD CONSTRAINT PUBLIC.FK82N3LX7TCHTIQXSD1YX4RY9Q0 FOREIGN KEY(PERSON_ID) REFERENCES PUBLIC.T_PERSON(ID) NOCHECK;            
ALTER TABLE PUBLIC.T_VET_SPECIALTY ADD CONSTRAINT PUBLIC.FKSSPWDIIB10CRWOAMQ1T37XLF8 FOREIGN KEY(SPECIALTY_ID) REFERENCES PUBLIC.T_SPECIALTY(ID) NOCHECK;      
ALTER TABLE PUBLIC.T_IMAGE ADD CONSTRAINT PUBLIC.FKPXH6EFI2YH33N2O4UY5NWH2A7 FOREIGN KEY(CONTENT_ID) REFERENCES PUBLIC.T_IMAGE_CONTENT(ID) NOCHECK;              
ALTER TABLE PUBLIC.T_ADDRESS ADD CONSTRAINT PUBLIC.FKO1IT862NQ27JI8WQ4XVPIOBHC FOREIGN KEY(PERSON_ID) REFERENCES PUBLIC.T_PERSON(ID) NOCHECK;  
ALTER TABLE PUBLIC.T_PET ADD CONSTRAINT PUBLIC.FKCOWCHY6T1QBD40T4NYT6BC28P FOREIGN KEY(TYPE_ID) REFERENCES PUBLIC.T_PET_TYPE(ID) NOCHECK;      
ALTER TABLE PUBLIC.T_CLINIC_PERSON ADD CONSTRAINT PUBLIC.FKMLX7FETTXE05PML37I9B2VJ71 FOREIGN KEY(CLINIC_ID) REFERENCES PUBLIC.T_CLINIC(ID) NOCHECK;            
ALTER TABLE PUBLIC.T_ADDRESS ADD CONSTRAINT PUBLIC.FK3FOP8LBKMUVRG7MXH63OK59D0 FOREIGN KEY(CITY_ID) REFERENCES PUBLIC.T_CITY(ID) NOCHECK;      
ALTER TABLE PUBLIC.T_PET ADD CONSTRAINT PUBLIC.FKPW0U24HMPXTA2O8BHR3KELM1H FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.T_OWNER(ID) NOCHECK;        
ALTER TABLE PUBLIC.T_VISIT ADD CONSTRAINT PUBLIC.FK1QLJVSQ8TWIG8QXW4OCQBR2VN FOREIGN KEY(PET_ID) REFERENCES PUBLIC.T_PET(ID) NOCHECK;          
ALTER TABLE PUBLIC.T_OWNER ADD CONSTRAINT PUBLIC.FKAQQ09U9HVIYX1RD00G5I7VH3D FOREIGN KEY(ID) REFERENCES PUBLIC.T_PERSON(ID) NOCHECK;           
ALTER TABLE PUBLIC.T_VET_SPECIALTY ADD CONSTRAINT PUBLIC.FKK7BVXL60BSN3EYEJ0HCV7RAG2 FOREIGN KEY(VET_ID) REFERENCES PUBLIC.T_VET(ID) NOCHECK;  
ALTER TABLE PUBLIC.T_IMAGE ADD CONSTRAINT PUBLIC.FKJ3W3RFP28XJV01E5GXGWDE2JG FOREIGN KEY(PET_ID) REFERENCES PUBLIC.T_PET(ID) NOCHECK;          
